# Generated by Django 5.2.3 on 2025-07-10 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaChamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='prioridadechamado',
            name='chamado',
        ),
        migrations.RemoveField(
            model_name='statuschamado',
            name='chamado',
        ),
        migrations.AddField(
            model_name='chamado',
            name='prioridade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados', to='Calls.prioridadechamado'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados', to='Calls.statuschamado'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='categoriaChamado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados', to='Calls.categoriachamado'),
        ),
    ]
