# Generated by Django 5.2.3 on 2025-07-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calls', '0002_categoriachamado_remove_prioridadechamado_chamado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posto_grad',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='nome_de_guerra',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
