# Generated by Django 5.2.3 on 2025-07-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calls', '0003_alter_posto_grad_nome_alter_user_nome_de_guerra'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagemchamado',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='mensagens/'),
        ),
        migrations.AddField(
            model_name='mensagemchamado',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='mensagens/'),
        ),
    ]
