# Generated by Django 5.2.3 on 2025-07-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calls', '0004_mensagemchamado_imagem_mensagemchamado_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagemchamado',
            name='visualizado',
            field=models.BooleanField(default=False),
        ),
    ]
