# Generated by Django 5.2.3 on 2025-07-29 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calls', '0005_mensagemchamado_visualizado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensagemchamado',
            name='visualizado',
        ),
    ]
