# Generated by Django 5.2.3 on 2025-07-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calls', '0006_remove_mensagemchamado_visualizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagemchamado',
            name='visualizado',
            field=models.BooleanField(default=False),
        ),
    ]
